# Generated by Django 5.1.15 on 2026-09-19 22:35

import django.db.models.deletion
import play.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('phone', 'phone'), ('edi', 'edi'), ('bishop', 'bishop'), ('pi', 'pi'), ('pc', 'pc')], default='pc', max_length=16)),
                ('token', models.CharField(default=play.models.gen_token, max_length=64, unique=True)),
                ('rate_limit_sec', models.IntegerField(default=300)),
                ('boost_interval_sec', models.IntegerField(default=20)),
                ('boosted_until', models.DateTimeField(blank=True, null=True)),
                ('last_snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnedBeast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_id', models.CharField(max_length=32)),
                ('id_version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=64)),
                ('rarity', models.CharField(max_length=16)),
                ('shiny', models.BooleanField(default=False)),
                ('level', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('wild', 'wild'), ('owned', 'owned')], default='wild', max_length=8)),
                ('species_json', models.JSONField()),
                ('individual_json', models.JSONField()),
                ('caught_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='play.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-caught_at'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(max_length=16)),
                ('entropy', models.FloatField(default=0)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='play.node')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shards', models.IntegerField(default=50)),
                ('cores', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=64)),
                ('qty', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'item_id')},
            },
        ),
    ]
