# Generated by Django 5.1.15 on 2026-09-19 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='team_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='node',
            name='kind',
            field=models.CharField(default='node', max_length=16),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='BattleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=64)),
                ('result', models.CharField(max_length=8)),
                ('turns', models.IntegerField(default=0)),
                ('reward', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TradeListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('is_open', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('beast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='play.ownedbeast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('declined', 'declined')], default='pending', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='play.tradelisting')),
                ('offered_beast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_in', to='play.ownedbeast')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
