# Generated by Django 5.1.15 on 2026-09-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_wallet_team_ids_alter_node_kind_alter_node_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='rate_limit_sec',
            field=models.IntegerField(default=60),
        ),
    ]
