# Generated by Django 5.1.15 on 2026-09-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_asyncbattle_ladderteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedbeast',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='wallet',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
