# Generated by Django 5.1.15 on 2026-09-20 21:17

from django.db import migrations, models


def grandfather_snapshot_beasts(apps, schema_editor):
    """Pre-existing beasts caught through a node snapshot (site-generated, no import source_id) are legit
    finds — keep them tradeable. Imported beasts (source_id set) stay unverified."""
    OwnedBeast = apps.get_model("play", "OwnedBeast")
    OwnedBeast.objects.filter(source_id="").update(verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_ownedbeast_source_id_wallet_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedbeast',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(grandfather_snapshot_beasts, migrations.RunPython.noop),
    ]
