# Generated by Django 5.1.15 on 2026-09-20 21:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_ownedbeast_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buddy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.IntegerField(default=60)),
                ('relationship', models.IntegerField(default=0)),
                ('hunger', models.IntegerField(default=60)),
                ('energy', models.IntegerField(default=70)),
                ('cleanliness', models.IntegerField(default=80)),
                ('last_care', models.JSONField(default=dict)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('refreshed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slotted_at', models.DateTimeField(blank=True, null=True)),
                ('beast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='play.ownedbeast')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buddy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
