# Generated by Django 5.1.15 on 2026-09-20 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0007_buddy'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddy',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='play.node'),
        ),
    ]
