# Generated by Django 5.1.15 on 2026-09-20 21:58

from django.db import migrations, models


def grandfather_existing_paid(apps, schema_editor):
    """New default is free (subscribed=False). Grandfather everyone who already had an account to paid,
    so the current (sole) account keeps full access; new signups start on the free tier."""
    Wallet = apps.get_model("play", "Wallet")
    Wallet.objects.update(subscribed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0008_buddy_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(grandfather_existing_paid, migrations.RunPython.noop),
    ]
