# Generated by Django 5.1.15 on 2026-09-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0009_alter_wallet_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
