# Generated by Django 5.1.15 on 2026-09-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0010_wallet_last_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='wallet',
            name='subscription_status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
