# Generated by Django 5.1.15 on 2026-09-21 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0011_wallet_onboarded_wallet_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeoffer',
            name='offered_beasts',
            field=models.ManyToManyField(blank=True, related_name='offered_in_set', to='play.ownedbeast'),
        ),
        migrations.AddField(
            model_name='tradeoffer',
            name='offered_cores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tradeoffer',
            name='offered_shards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tradeoffer',
            name='offered_beast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_in', to='play.ownedbeast'),
        ),
    ]
