# Generated by Django 5.1.15 on 2026-09-21 07:57

from django.db import migrations, models


def bump_existing(apps, schema_editor):
    # Elongate submit rate limits 5x for nodes created before this change (buddy actions unaffected).
    Node = apps.get_model('play', 'Node')
    for n in Node.objects.all():
        n.rate_limit_sec = (n.rate_limit_sec or 60) * 5
        n.boost_interval_sec = (n.boost_interval_sec or 20) * 5
        n.save(update_fields=['rate_limit_sec', 'boost_interval_sec'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0012_tradeoffer_offered_beasts_tradeoffer_offered_cores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='boost_interval_sec',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='node',
            name='rate_limit_sec',
            field=models.IntegerField(default=300),
        ),
        migrations.RunPython(bump_existing, noop),
    ]
