# Generated by Django 5.1.15 on 2026-09-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0013_bump_node_rate_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedbeast',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
