# Generated by Django 5.1.15 on 2026-09-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0014_beast_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddy',
            name='cleanliness',
            field=models.FloatField(default=80),
        ),
        migrations.AlterField(
            model_name='buddy',
            name='energy',
            field=models.FloatField(default=70),
        ),
        migrations.AlterField(
            model_name='buddy',
            name='hunger',
            field=models.FloatField(default=60),
        ),
        migrations.AlterField(
            model_name='buddy',
            name='mood',
            field=models.FloatField(default=60),
        ),
    ]
