# Generated by Django 5.1.15 on 2026-09-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0015_alter_buddy_cleanliness_alter_buddy_energy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='client_app',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='node',
            name='client_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='client_version',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
