# Generated by Django 5.1.15 on 2026-09-23 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0016_node_client_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='heartbeat_sec',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='last_error',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='node',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='scan_mode',
            field=models.CharField(default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='node',
            name='sensors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='ownedbeast',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownedbeast',
            name='field_notes',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='ownedbeast',
            name='journal_data',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='ActivityEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('kind', models.CharField(max_length=32)),
                ('summary', models.CharField(max_length=300)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('beast_key', models.CharField(blank=True, max_length=64)),
                ('changes', models.JSONField(default=dict)),
                ('balances', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['user', '-id'], name='play_activi_user_id_412d92_idx')],
            },
        ),
    ]
