# Generated by Django 5.1.15 on 2026-10-08 03:11

import django.db.models.deletion
import play.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0018_activity_opening_balances'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='billing_provider',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.CreateModel(
            name='LinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=play.models.gen_link_code, max_length=43, unique=True)),
                ('state', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_codes', to='play.node')),
            ],
        ),
    ]
