# Generated by Django 5.1.15 on 2026-10-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0019_linkcode_wallet_billing_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='play_auto_renewing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='play_base_plan',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='wallet',
            name='play_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='play_linked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='play_obfuscated_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='wallet',
            name='play_product_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='wallet',
            name='play_purchase_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=512),
        ),
    ]
